-- Premium subscription support
-- Run this once in Supabase Studio → SQL Editor

-- 1. Plan column on profiles ('free' | 'premium')
alter table public.profiles
  add column if not exists plan text not null default 'free';

-- 2. Upgrade requests (users tap "Get Premium" in the app)
create table if not exists public.subscription_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  plan text not null,
  created_at timestamptz not null default now()
);

alter table public.subscription_requests enable row level security;

drop policy if exists "users can request" on public.subscription_requests;
create policy "users can request" on public.subscription_requests
  for insert with check (auth.uid() = user_id);

drop policy if exists "admins can read requests" on public.subscription_requests;
create policy "admins can read requests" on public.subscription_requests
  for select using (
    exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.is_admin)
  );

-- 3. Admins can change any user's plan (needed by the admin panel toggle)
drop policy if exists "admins can update plans" on public.profiles;
create policy "admins can update plans" on public.profiles
  for update using (
    exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.is_admin)
  );
